#!/usr/bin/env python3
"""Extract the ADV keyboard matrix from the VENDOR header and emit web/keymap.js.

WHY: the browser keyboard must be the same 4x14 matrix the firmware reads. If it
were transcribed by hand it would drift the first time M5Stack revised a key.
This parses _key_value_map[4][14] out of M5Cardputer's Keyboard.h, so a library
bump regenerates the web layout automatically.

Coordinates are [row][col], confirmed by Keyboard.cpp:47:
    _key_value_map[keyCoor.y][keyCoor.x]   with y=row, x=col
"""
import re, json, pathlib, sys

root = pathlib.Path(__file__).resolve().parent.parent
KB = root / ".pio/libdeps/cardputer-adv/M5Cardputer/src/utility/Keyboard/Keyboard.h"
if not KB.exists():
    sys.exit(f"vendor header not found: {KB}\nrun a build first so libdeps is populated")

src = KB.read_text()
m = re.search(r'_key_value_map\[4\]\[14\]\s*=\s*(.*?)\};\s*\n\s*class', src, re.S)
if not m:
    sys.exit("could not locate _key_value_map -- vendor layout changed, fix this parser")

pat = re.compile(r"\{\s*(KEY_[A-Z_]+|'(?:\\.|[^'])')\s*,\s*(KEY_[A-Z_]+|'(?:\\.|[^'])')\s*\}")
entries = pat.findall(m.group(1))
if len(entries) != 56:
    sys.exit(f"expected 56 keys, parsed {len(entries)} -- refusing to emit a wrong layout")


# Display labels for the vendor's control macros.
# Coordinates verified against Keyboard.h and the TCA8418 7x8 -> 4x14 remap:
# 56 raw positions map bijectively onto the 56 keymap cells, so no 57th key
# exists -- the arrows are these four, legended on the keycaps.
ARROW_CAP = {
    (2, 11): "\u2191",   # up
    (3, 10): "\u2190",   # left
    (3, 11): "\u2193",   # down
    (3, 12): "\u2192",   # right
}

LABEL = {
    "KEY_BACKSPACE": "del", "KEY_TAB": "tab", "KEY_ENTER": "enter",
    "KEY_FN": "fn", "KEY_OPT": "opt",
    # "Aa" is what the ADV silkscreens on the shift cap (see the product photo);
    # "shift" was my own wording and does not match the physical key.
    "KEY_LEFT_SHIFT": "Aa", "KEY_LEFT_CTRL": "ctrl", "KEY_LEFT_ALT": "alt",
}
# Keys that are modifiers, not characters -- the UI latches these.
MODS = {"KEY_FN": "fn", "KEY_LEFT_SHIFT": "shift",
        "KEY_LEFT_CTRL": "ctrl", "KEY_LEFT_ALT": "alt", "KEY_OPT": "opt"}

def lit(tok):
    if tok.startswith("KEY_"):
        return tok
    inner = tok[1:-1]
    return {"\\\\": "\\", "\\'": "'", '\\"': '"'}.get(inner, inner)

# ARROW_CAP is a hardcoded coordinate table -- right today, silently wrong after
# a vendor bump. Verify each cell still decodes to the character we believe it
# does, and refuse to emit if not. Compare through lit(), the same decoder the
# emitter uses, so the guard cannot pass while the emitted layout is wrong.
EXPECT_AT = {(2, 11): ";", (3, 10): ",", (3, 11): ".", (3, 12): "/"}
for (_r, _c), _ch in EXPECT_AT.items():
    _got = lit(entries[_r * 14 + _c][0])
    if _got != _ch:
        sys.exit(f"arrow legend guard: expected {_ch!r} at row {_r} col {_c}, "
                 f"found {_got!r}. The vendor keymap moved -- re-check ARROW_CAP "
                 f"against the physical keycaps before emitting.")

rows = []
for r in range(4):
    row = []
    for c in range(14):
        a, b = (lit(x) for x in entries[r * 14 + c])
        macro = entries[r * 14 + c][0]
        row.append({
            "r": r, "c": c,
            "lo": LABEL.get(a, a),
            # Keycap legend where the ADV silkscreens something other than the
            # character it reports. The arrow cluster is the whole reason this
            # field exists: those four keys are DEDICATED arrows on the ADV --
            # an inverted-T -- that happen to report as ; , . / because the
            # library reuses the classic Cardputer's value map. Showing the
            # punctuation made a real arrow key look like it did not exist.
            **({"cap": ARROW_CAP[(r, c)]} if (r, c) in ARROW_CAP else {}),
            "hi": LABEL.get(b, b),
            "mod": MODS.get(macro, None),
        })
    rows.append(row)

# Physical width units. The ADV keyboard is a uniform grid EXCEPT that row 3
# ends with a wide space bar occupying the last two positions; the vendor map
# stores ' ' at col 13 only. Keep the data honest: emit real coordinates, and
# let the CSS widen the space key rather than fabricating a 15th column.
out = root / "web" / "keymap.js"
out.write_text(
    "// AUTO-GENERATED by tools/gen_keymap.py from M5Cardputer Keyboard.h.\n"
    "// Do not edit -- rerun the generator instead.\n"
    "// Plain global, not an ES export: the firmware serves exactly one route\n"
    "// (\"/\"), so this file is INLINED into index.html by gen_web_assets.py.\n"
    "// A separate <script src> would 404 on the device.\n"
    "window.KEYMAP = " + json.dumps(rows, indent=0).replace("\n", "") + ";\n"
)
print(f"keymap.js  4x14 = {sum(len(r) for r in rows)} keys -> {out}")
