#!/usr/bin/env python3
"""Gzip web/index.html into a PROGMEM C header for the firmware to serve."""
import gzip, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
html = (root / "web" / "index.html").read_text()

# Inline the generated keymap. The firmware serves only "/", so an external
# <script src="keymap.js"> would 404 on the device. The placeholder keeps the
# page usable when opened directly from disk during development.
KM = "/*__KEYMAP__*/"
if KM not in html:
    raise SystemExit(f"index.html is missing the {KM} placeholder")
km = (root / "web" / "keymap.js")
if not km.exists():
    raise SystemExit("web/keymap.js missing - run tools/gen_keymap.py first")
html = html.replace(KM, km.read_text().strip())
raw  = html.encode()
gz   = gzip.compress(raw, 9)
body = "".join(("\n  " if i % 16 == 0 else "") + f"0x{b:02x}," for i, b in enumerate(gz))
# No embedded images: the Tab5 dashboard mockup (case + keyboard) is
# CSS-drawn, not a photo -- a photo-background first attempt didn't line up
# with the mirror canvas's actual 16:9 and cost ~79KB of flash on a device
# already tight on it. The Cardputer ADV's stamp.webp/advlabel.webp are also
# gone -- this repo targets Tab5 only, see docs/adr/0048-fork-for-tab5.md.

(root / "lib" / "CardputerMirror" / "WebAssets.h").write_text(
    "// AUTO-GENERATED by tools/gen_web_assets.py — do not edit.\n"
    "#pragma once\n#include <pgmspace.h>\n\n"
    f"static const size_t kIndexHtmlGzLen = {len(gz)};\n"
    "static const uint8_t kIndexHtmlGz[] PROGMEM = {" + body + "\n};\n")
print(f"index.html {len(raw):,} B -> gzip {len(gz):,} B ({len(gz)/len(raw)*100:.1f}%)")
