#!/usr/bin/env python3
"""Gzip web/index.html into a PROGMEM C header for the firmware to serve."""
import gzip, pathlib
root = pathlib.Path(__file__).resolve().parent.parent
html = (root / "web" / "index.html").read_text()

# Inline the generated keymap. The firmware serves only "/", so an external
# <script src="keymap.js"> would 404 on the device. The placeholder keeps the
# page usable when opened directly from disk during development.
KM = "/*__KEYMAP__*/"
if KM not in html:
    raise SystemExit(f"index.html is missing the {KM} placeholder")
km = (root / "web" / "keymap.js")
if not km.exists():
    raise SystemExit("web/keymap.js missing - run tools/gen_keymap.py first")
html = html.replace(KM, km.read_text().strip())
raw  = html.encode()
gz   = gzip.compress(raw, 9)
body = "".join(("\n  " if i % 16 == 0 else "") + f"0x{b:02x}," for i, b in enumerate(gz))
# The Stamp-S3A label photo. Embedded as its own PROGMEM array and served on
# its own route -- NOT base64-inlined into the page. Base64 costs 33% on bytes
# that are already compressed, so inlining would add ~22 KB of incompressible
# payload to every page load; as a separate resource the browser caches it.
IMAGES = [("stamp.webp",    "kStampWebp",    "ADR 0033"),
          ("advlabel.webp", "kAdvLabelWebp", "ADR 0035")]
chunks, report = [], []
for fn, sym, adr in IMAGES:
    p = root / "web" / fn
    if not p.exists():
        raise SystemExit(f"web/{fn} missing - see {adr}")
    ib = p.read_bytes()
    ibody = "".join(("\n  " if i % 16 == 0 else "") + f"0x{b:02x}," for i, b in enumerate(ib))
    chunks.append(f"static const size_t {sym}Len = {len(ib)};\n"
                  f"static const uint8_t {sym}[] PROGMEM = {{" + ibody + "\n};\n")
    report.append(f"{fn} {len(ib):,} B (served as-is)")

(root / "lib" / "CardputerMirror" / "WebAssets.h").write_text(
    "// AUTO-GENERATED by tools/gen_web_assets.py — do not edit.\n"
    "#pragma once\n#include <pgmspace.h>\n\n"
    f"static const size_t kIndexHtmlGzLen = {len(gz)};\n"
    "static const uint8_t kIndexHtmlGz[] PROGMEM = {" + body + "\n};\n\n"
    + "\n".join(chunks))
print(f"index.html {len(raw):,} B -> gzip {len(gz):,} B ({len(gz)/len(raw)*100:.1f}%)")
for r in report: print(r)
